### ISSUE TITLE
500 Error on SvelteKit: `Cannot read property 'length' of undefined`

### ISSUE THREAD

**Issue by mr-islam** [vincjo/svelte-simple-datatables#45]
Just installed v0.2.1 and I get the following error, even when creating a brand new repo with nothing else

````
500
Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at Proxy.each (C:\Code\jummal\node_modules\svelte\internal\index.js:1710:31)
    at Object.default (SavedValues.svelte:37:10)
    at Datatable.svelte:48:15
    at Object.$$render (C:\Code\jummal\node_modules\svelte\internal\index.js:1745:22)
    at eval (/src/components/SavedValues.svelte:117:106)
    at Object.$$render (C:\Code\jummal\node_modules\svelte\internal\index.js:1745:22)
    at eval (/src/routes/index.svelte:23:90)
    at Object.$$render (C:\Code\jummal\node_modules\svelte\internal\index.js:1745:22)
    at Object.default (root.svelte:43:47)
    at eval (/.svelte-kit/runtime/components/layout.svelte:8:41)
````

EDIT: 

I tried using the exact examples from the docs:

````
<script>
	import { Datatable } from 'svelte-simple-datatables';
	const settings = { columnFilter: true };
	let rows;
	let data = [
		{ id: 1, first_name: 'Tobie', last_name: 'Vint', email: 'tvint0@fotki.com' },
		{ id: 2, first_name: 'Zacharias', last_name: 'Cerman', email: 'zcerman1@sciencedirect.com' },
		{ id: 3, first_name: 'Gerianna', last_name: 'Bunn', email: 'gbunn2@foxnews.com' },
		{ id: 4, first_name: 'Bee', last_name: 'Saurin', email: 'bsaurin3@live.com' },
		{ id: 5, first_name: 'Meyer', last_name: 'Garnul', email: 'mgarnul4@yellowbook.com' },
		{ id: 6, first_name: 'Frederich', last_name: 'Benley', email: 'fbenley5@ameblo.jp' },
		{ id: 7, first_name: 'Becki', last_name: 'Criag', email: 'bcriag6@washingtonpost.com' },
		{ id: 8, first_name: 'Nichols', last_name: 'Risom', email: 'nrisom7@google.com.br' },
		{ id: 9, first_name: 'Ron', last_name: 'Menendes', email: 'rmenendes8@prnewswire.com' },
		{ id: 10, first_name: 'Thane', last_name: 'Gammill', email: 'tgammill9@com.com' },
		{ id: 11, first_name: 'Ramonda', last_name: 'Yakobowitch', email: 'ryakobowitcha@hibu.com' },
		{
			id: 12,
			first_name: 'Rosalynd',
			last_name: 'Connechie',
			email: 'rconnechieb@chicagotribune.com'
		},
		{ id: 13, first_name: 'Vinny', last_name: 'Hissett', email: 'vhissettc@4shared.com' },
		{ id: 14, first_name: 'Mylo', last_name: 'Tarbath', email: 'mtarbathd@behance.net' }
	];
</script>

<Datatable {settings} {data} bind:dataRows={rows}>
	<thead>
		<th data-key="id">ID</th>
		<th data-key="first_name">First Name</th>
		<th data-key="last_name">Last Name</th>
		<th data-key="email">Email</th>
	</thead>
	<tbody>
		{#if rows}
			{#each $rows as row}
				<tr>
					<td>{row.id}</td>
					<td>{row.first_name}</td>
					<td>{row.last_name}</td>
					<td>{row.email}</td>
				</tr>
			{/each}
		{/if}
	</tbody>
</Datatable>

<style>
	th:first-child {
		width: 72px;
	}
	td {
		text-align: center;
		padding: 4px 0;
	}
</style>
````

**Comment by mr-islam** [comment]
Thank you for your super fast help! 🌹

I tried re-configuring my dev environment, and putting the table component on another route did the trick

**Comment by Kaydax** [comment]
I'm still getting this exact issue no matter what I try. I tried putting it in a seperate route / lib svelte file and it produces this exact error every time

**Comment by mr-islam** [comment]
Have you tried calling it only when mounted? Something like:

````
<script>
    	import db from '../components/db.svelte';
	import { onMount } from 'svelte';

	onMount(() => {
		mounted = true;
	});
	let mounted = false;
</script>

{#if mounted}
<db />

{/if}
````

**Comment by Kaydax** [comment]
Yah that seems to have fixed it. Very odd that this is the issue though, but thank you

**Comment by mr-islam** [comment]
For sure there are some kinks in SvelteKit and interactions with libraries, or at least in my understanding of them 😅
